#-*- coding:utf-8 -*-

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import math

def is_triangle(n):
    x = int((math.sqrt(8 * n + 1) - 1) / 2)
    if x * (x + 1) / 2 == n:
        return True
    return False


def is_pentagonal(n):
    x = int((math.sqrt(24 * n + 1) + 1) / 6)
    if x * (x * 3 - 1) / 2 == n:
        return True
    return False


def main():
    for i in xrange(144, 100000):
        hexagoanl = i * (2 * i - 1)
        if is_triangle(hexagoanl) and is_pentagonal(hexagoanl):
            print hexagoanl
            break


if __name__ == '__main__':
    main()
